// @ts-check
import { defineConfig } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default defineConfig(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'src-tauri',
      'crates',
      'target',
      'e2e',
      'scripts',
      // Generated by ts-rs from the Rust types — never hand-edited or linted.
      'src/ipc/gen',
    ],
  },
  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ['eslint.config.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      // `||` on strings is usually the intent (empty string → fallback).
      '@typescript-eslint/prefer-nullish-coalescing': [
        'error',
        { ignorePrimitives: { string: true } },
      ],
      // `invoke<void>(…)` is the canonical Tauri command signature.
      '@typescript-eslint/no-invalid-void-type': ['error', { allowInGenericTypeArguments: true }],
      // Counts inside copy templates are the whole point of §A strings.
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
    },
  },
  {
    // `invoke<void>` is the canonical Tauri command signature; the rule
    // misfires on it here despite allowInGenericTypeArguments.
    files: ['src/ipc/commands.ts'],
    rules: { '@typescript-eslint/no-invalid-void-type': 'off' },
  },
  {
    // Tests assert on elements that provably exist; `!` beats casts there.
    files: ['**/*.test.{ts,tsx}', 'src/test/**'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },
  {
    // The config file itself is plain JS; typed rules don't apply cleanly.
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  prettier,
);
