// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `apply-finished` payload (§8.5 step 4): the cleared/kept flags are true
 * only if rules were actually non-empty, so applying pure manual edits
 * claims neither.
 */
export type ApplyFinished = { 
/**
 * How many items were renamed.
 */
count: number, 
/**
 * The recorded snapshot, when anything succeeded.
 */
snapshotId: string | null, 
/**
 * Whether this was a Folders-mode apply.
 */
isFolders: boolean, 
/**
 * The rule stack was cleared (⌘Z restores it).
 */
clearedRules: boolean, 
/**
 * The rule stack was kept; renamed files deselected.
 */
keptRules: boolean, };
