// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `get_platform` payload — drives per-OS UI copy (§12.1).
 */
export type PlatformInfo = { 
/**
 * `"macos"` / `"windows"` / `"linux"`.
 */
os: string, 
/**
 * `"direct"` / `"mas"` / `"msstore"` / `"flathub"` (§20.1).
 */
channel: string, 
/**
 * Whether `{md:…}` comes from Spotlight (inspector section title).
 */
hasSpotlight: boolean, 
/**
 * App version.
 */
version: string, };
