// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevertStatus } from "./RevertStatus";

/**
 * One row of the revert preview (§8.8).
 */
export type RevertEntry = { 
/**
 * `{snapshotId}-{offset}` — stable row identity for the UI.
 */
id: string, 
/**
 * The snapshot this entry belongs to.
 */
snapshotId: string, 
/**
 * When that snapshot was applied.
 */
snapshotDate: string, 
/**
 * The directory the rename lives in (for grouping).
 */
directoryPath: string, 
/**
 * The name the file has now.
 */
currentName: string, 
/**
 * The name the revert would restore.
 */
restoredName: string, 
/**
 * What the revert will do with this entry.
 */
status: RevertStatus, };
