// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One history row (§12.1 `get_history`).
 */
export type SnapshotMeta = { id: string, date: string, summary: string, entryCount: number, };
