// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileItem } from "./FileItem";
import type { FileSortKey } from "./FileSortKey";
import type { ListMode } from "./ListMode";
import type { RenameRule } from "./RenameRule";
import type { RulePreset } from "./RulePreset";
import type { WatchedFolder } from "./WatchedFolder";

/**
 * The full state mirror the frontend refreshes on `state-changed` (§13.1).
 */
export type StateSnapshot = { 
/**
 * Every tracked item, insertion order.
 */
files: Array<FileItem>, 
/**
 * The rule stack.
 */
rules: Array<RenameRule>, 
/**
 * Watched folder roots.
 */
watchedFolders: Array<WatchedFolder>, 
/**
 * Saved presets (menu contents).
 */
presets: Array<RulePreset>, 
/**
 * §4.1 scalars.
 */
trimsWhitespace: boolean, autoResolvesConflicts: boolean, keepRulesAfterApply: boolean, includeSubfolders: boolean, sortKey: FileSortKey, sortAscending: boolean, listMode: ListMode, selectedSnapshotId: string | null, rulesClearedByApply: boolean, 
/**
 * Bumped by every mutation (§13.1 out-of-order guard).
 */
version: bigint, 
/**
 * Reconciles the optimistic rules draft (§13.1).
 */
rulesRevision: bigint, 
/**
 * Whether an Apply/Revert is in flight (menu/action gating).
 */
isProcessing: boolean, 
/**
 * Manual overrides in the active mode (the `{N} edited` chip).
 */
overrideCount: number, 
/**
 * History count (side-tab badge).
 */
historyCount: number, 
/**
 * Edit-menu label for Undo, when available.
 */
undoAction: string | null, 
/**
 * Edit-menu label for Redo, when available.
 */
redoAction: string | null, };
