// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the user imported: watched live, its contents populate the list.
 */
export type WatchedFolder = { 
/**
 * Stable identity, preserved across path rewrites.
 */
id: string, 
/**
 * Absolute path of the watched root.
 */
path: string, 
/**
 * Per-folder subfolder override; `None` follows the global toggle (§9).
 */
includeSubfolders: boolean | null, };
