// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsvMatch } from "./CsvMatch";
import type { CsvMiss } from "./CsvMiss";

/**
 * The dry-run report powering the Rename by CSV modal — computing it
 * mutates NOTHING (§24 Q30).
 */
export type CsvMatchReport = { 
/**
 * Every matched item with its assigned name.
 */
matches: Array<CsvMatch>, 
/**
 * Rows that won't apply, grouped by the UI per reason.
 */
misses: Array<CsvMiss>, 
/**
 * Matched items whose name will change (the `{A}` in the modal).
 */
willChange: number, 
/**
 * Matched items whose assigned name equals their current name.
 */
unchanged: number, };
