// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsvMissReason } from "./CsvMissReason";

/**
 * One row that won't apply, with its reason.
 */
export type CsvMiss = { 
/**
 * The row's current-name column (or the raw line for unreadable rows).
 */
name: string, 
/**
 * Why it won't apply.
 */
reason: CsvMissReason, };
