// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewCounts } from "./PreviewCounts";
import type { PreviewEntry } from "./PreviewEntry";
import type { RuleImpact } from "./RuleImpact";

/**
 * The full preview payload.
 */
export type Preview = { 
/**
 * One entry per active item, in view order.
 */
entries: Array<PreviewEntry>, 
/**
 * Per-rule impact counts, in stack order (disabled rules count 0).
 */
ruleImpact: Array<RuleImpact>, 
/**
 * Derived counts (§7.7).
 */
counts: PreviewCounts, };
