// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevertEntry } from "./RevertEntry";

/**
 * The full revert-preview payload with its derived counts (§8.8).
 */
export type RevertPreview = { 
/**
 * Every affected rename, newest snapshot first.
 */
entries: Array<RevertEntry>, 
/**
 * Renames that will be restored (`Ok` entries).
 */
restorableRenameCount: number, 
/**
 * Distinct files restored — `Ok` chain heads: N versions touching one
 * file count as 1 file, not N.
 */
restorableFileCount: number, 
/**
 * Entries whose original name is taken.
 */
nameTakenCount: number, 
/**
 * How many newer snapshots the revert also undoes.
 */
newerSnapshotCount: number, };
