// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many items one rule actually changed (§7.9); drives the rule-card
 * `affects 14 of 20` header.
 */
export type RuleImpact = { 
/**
 * The rule this impact belongs to.
 */
ruleId: string, 
/**
 * Items whose name this rule changed at its stage.
 */
affected: number, 
/**
 * Selected, non-overridden active items.
 */
eligible: number, };
