// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The ten rule kinds. Serialized values are the legacy camelCase strings —
 * presets are portable files users may already have (§4.2).
 */
export type RuleKind = "removeText" | "replaceText" | "regexReplace" | "addPrefix" | "addSuffix" | "changeCase" | "changeExtension" | "sanitize" | "numberSequentially" | "template";
