// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotEntry } from "./SnapshotEntry";

/**
 * One applied batch: every rename it performed, revertible later (§4.3).
 */
export type Snapshot = { 
/**
 * Stable identity.
 */
id: string, 
/**
 * When the batch was applied (UTC).
 */
date: string, 
/**
 * ` · `-joined description of what the batch did (§8.1).
 */
summary: string, 
/**
 * The renames, in execution order.
 */
entries: Array<SnapshotEntry>, };
