// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded rename in a snapshot: absolute old and new paths.
 */
export type SnapshotEntry = { 
/**
 * Absolute path before the rename.
 */
from: string, 
/**
 * Absolute path after the rename.
 */
to: string, };
